/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package instructordashboard;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import loginsignup.LoginForm;
import model.Instructor;
import studentdashboard.StudentDashboard;
import utilities.Connection;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.ImageIcon;



/**
 *
 * @author Dell
 */
public class InstructorDashboard extends javax.swing.JFrame {
	

    private String username;
    private String userType;
    private String sql = "";
    private Instructor instructor;
    
    
    

    /**
     * Creates new form InstructorDashboard
     */
    public InstructorDashboard(String username, String userType) {
        this.username = username;
        this.userType = userType;
        initComponents();
        myInitComponentFirst();
        instructorFullnameValue.setText(instructor.getFirstName().toUpperCase() + " " + instructor.getLastName().toUpperCase());
        instructorEmailValue.setText(instructor.getEmail());
        instructorUsernameValue.setText(username);
       
    }

    public InstructorDashboard() {
        initComponents();
    }

    private void myInitComponentFirst() {
        instructor = getAllInstructorValues();
        setupTableValues();
        

    }

    public Instructor getAllInstructorValues() {
        Instructor ins = new Instructor();
        try {
            java.sql.Connection conn = Connection.getConnection();

//            if (userType.toLowerCase().equals("student")) {
//                sql = "SELECT * FROM STUDENT WHERE USERNAME =? AND USER_TYPE =?";
//            } else if (userType.toLowerCase().equals("course administrator")) {
//                sql = "SELECT * FROM COURSE_ADMINISTRATOR WHERE USERNAME =? AND USER_TYPE =?";
//            } else {
//                sql = "SELECT * FROM INSTRUCTOR WHERE USERNAME =? AND USER_TYPE =?";
//            }
            sql = "SELECT * FROM INSTRUCTOR WHERE USERNAME =? AND USER_TYPE =?";

            PreparedStatement preparedStmt = conn.prepareStatement(sql);
            preparedStmt.setString(1, username);
            preparedStmt.setString(2, userType.toLowerCase());

            ResultSet rs = preparedStmt.executeQuery();

            if (rs.next()) {
                ins.setFirstName(rs.getString("firstname"));
                ins.setLastName(rs.getString("lastname"));
                ins.setEmail(rs.getString("email"));
                ins.setId(rs.getInt("id"));
                return ins;
            } else {
                JOptionPane.showMessageDialog(this, "Details not found !");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ins;
    }

    private void setupTableValues() {

        try {
            java.sql.Connection conn = Connection.getConnection();

            String sql = "SELECT course.id AS courseId, course.name AS courseName, modules.id AS moduleId, modules.name AS moduleName, modules.level AS LEVEL FROM modules INNER JOIN COURSE ON course.id = modules.course_id INNER JOIN instructor ON instructor.id = modules.instructor_id WHERE instructor.id =  " + this.instructor.getId();

            PreparedStatement preparedStmt = conn.prepareStatement(sql);

            ResultSet rs = preparedStmt.executeQuery();

            System.out.println(rs);
            while (rs.next()) {
                String courseId = String.valueOf(rs.getString("courseId"));
                String moduleId = String.valueOf(rs.getString("moduleId"));
                String courseName = rs.getString("courseName");
                String moduleName = rs.getString("moduleName");
                String moduleLevel = String.valueOf(rs.getString("level"));

                String tbData[] = {courseId, courseName, moduleId, moduleName, moduleLevel};
                DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
                tbl.addRow(tbData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboardHeader = new javax.swing.JLabel();
        dashboardSubheader = new javax.swing.JLabel();
        dashboardSubheader.setFont(new Font("Tahoma", Font.BOLD, 14));
        dashboardSubheader.setIcon(null);
        dashboardButton = new javax.swing.JButton();
        dashboardButton.setIcon(new ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\CMS-main\\icons8-dashboard-48.png"));
        logoutButton = new javax.swing.JButton();
        logoutButton.setIcon(new ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\CMS-main\\logout12.png"));
        jPanel2 = new javax.swing.JPanel();
        instructorFullnameLabel = new javax.swing.JLabel();
        instructorFullnameValue = new javax.swing.JLabel();
        instructorUsernameValue = new javax.swing.JLabel();
        instructorUsernameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        instructorEmailLabel = new javax.swing.JLabel();
        instructorEmailValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(175, 167, 187));

        dashboardHeader.setFont(new Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        dashboardHeader.setText("COURSE MANAGEMENT SYSTEM");

        dashboardSubheader.setText("Instructor");

        dashboardButton.setText("DASHBOARD");

        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        
        lblNewLabel_3 = new JLabel("New label");
        lblNewLabel_3.setIcon(new ImageIcon("C:\\Users\\ASUS\\Downloads\\icons8-teacher-64.png"));
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(51, Short.MAX_VALUE)
        			.addComponent(dashboardHeader)
        			.addGap(15))
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(35)
        			.addComponent(lblNewLabel_3, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(dashboardSubheader, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(102, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(56)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(logoutButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        				.addComponent(dashboardButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
        			.addGap(91))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(40)
        			.addComponent(dashboardHeader)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_3)
        				.addComponent(dashboardSubheader))
        			.addGap(177)
        			.addComponent(dashboardButton)
        			.addGap(30)
        			.addComponent(logoutButton)
        			.addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        instructorFullnameLabel.setForeground(new java.awt.Color(0, 0, 0));
        instructorFullnameLabel.setText("Instructor Fullname: ");

        instructorFullnameValue.setForeground(new java.awt.Color(0, 0, 0));

        instructorUsernameValue.setForeground(new java.awt.Color(0, 0, 0));

        instructorUsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        instructorUsernameLabel.setText("Instructor Username: ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Module Id", "Module Name", "Level"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modules Assigned");

        instructorEmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        instructorEmailLabel.setText("Instructor Email: ");
        instructorEmailLabel.setToolTipText("");

        instructorEmailValue.setForeground(new java.awt.Color(0, 0, 0));
        
        lblNewLabel = new JLabel("Herald College Kathmandu");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 16));
        
        lblNewLabel_2 = new JLabel("New label");
        lblNewLabel_2.setIcon(new ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\CMS-main\\icons8-courses-64.png"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(49, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(49)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(jPanel2Layout.createSequentialGroup()
        								.addComponent(instructorFullnameLabel)
        								.addPreferredGap(ComponentPlacement.UNRELATED)
        								.addComponent(instructorFullnameValue, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
        								.addGap(18)
        								.addComponent(instructorUsernameLabel)
        								.addPreferredGap(ComponentPlacement.UNRELATED)
        								.addComponent(instructorUsernameValue, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE))
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel2Layout.createSequentialGroup()
        									.addComponent(lblNewLabel_2, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE))
        								.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 594, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(instructorEmailLabel)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(instructorEmailValue, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(264)
        					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 237, GroupLayout.PREFERRED_SIZE)))
        			.addGap(46))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel)
        			.addGap(48)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(instructorFullnameLabel)
        				.addComponent(instructorFullnameValue, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        				.addComponent(instructorUsernameValue, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        				.addComponent(instructorUsernameLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(instructorEmailLabel)
        				.addComponent(instructorEmailValue, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE))
        			.addGap(44)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblNewLabel_2)
        				.addComponent(jLabel1))
        			.addGap(18)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 398, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setLocationRelativeTo(null);
        loginForm.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

            int column = 0;
            int row = jTable1.getSelectedRow();
            String courseId = jTable1.getValueAt(row, 0).toString();
            String courseName = jTable1.getValueAt(row, 1).toString();
            String moduleId = jTable1.getValueAt(row, 2).toString();
            String moduleName = jTable1.getValueAt(row, 3).toString();
            String level = jTable1.getValueAt(row, 4).toString();

            StudentInModuleListForm studentListForm = new StudentInModuleListForm(courseId, moduleId,courseName, moduleName, level);
            studentListForm.setLocationRelativeTo(null);
            studentListForm.setVisible(true);



    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardButton;
    private javax.swing.JLabel dashboardHeader;
    private javax.swing.JLabel dashboardSubheader;
    private javax.swing.JLabel instructorEmailLabel;
    private javax.swing.JLabel instructorEmailValue;
    private javax.swing.JLabel instructorFullnameLabel;
    private javax.swing.JLabel instructorFullnameValue;
    private javax.swing.JLabel instructorUsernameLabel;
    private javax.swing.JLabel instructorUsernameValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButton;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_2;
    private JLabel lblNewLabel_3;
}
